package rms

type Rms511 struct{}

// TOTAL_VENDIDO_DIA
func (r *Rms511) TOTAL_VENDIDO_DIA() string {
	return "SELECT COALESCE(SUM(A.DET_TOTAL), 0) AS VALOR FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND B.CAP_CANCELADO = 'N'"
}

// TICKET_MEDIO_DIA
func (r *Rms511) TICKET_MEDIO_DIA() string {
	return "SELECT ROUND(SUM(B.CAP_VLR_CUPOM) / COUNT(*), 2) AS TICKET FROM RMS.CAPCUPOM B WHERE B.CAP_DATA = :1 AND B.CAP_FILIAL = :2 AND B.CAP_CANCELADO = 'N'"
}

// PRODUTOS_POR_ATENDIMENTO_DIA
func (r *Rms511) PRODUTOS_POR_ATENDIMENTO_DIA() string {
	return "SELECT ROUND(COUNT(A.DET_EAN) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_PROD FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM C ON A.DET_FILIAL = C.CAP_FILIAL AND A.DET_DATA = C.CAP_DATA AND A.DET_NR_CUPOM = C.CAP_NR_CUPOM AND A.DET_NR_PDV = C.CAP_NR_PDV WHERE A.DET_CANCELADO = 'N' AND C.CAP_CANCELADO = 'N' AND A.DET_DATA = :1 AND A.DET_FILIAL = :2"
}

// TOTAL_CUPONS_VALIDOS_DIA
func (r *Rms511) TOTAL_CUPONS_VALIDOS_DIA() string {
	return "SELECT COUNT(*) AS CUPONS FROM RMS.CAPCUPOM WHERE CAP_DATA = :1 AND CAP_FILIAL = :2 AND CAP_CANCELADO = 'N'"
}

// TOTAL_CUPONS_CANCELADOS_DIA
func (r *Rms511) TOTAL_CUPONS_CANCELADOS_DIA() string {
	return "SELECT COUNT(*) AS CUPONS FROM RMS.CAPCUPOM WHERE CAP_DATA = :1 AND CAP_FILIAL = :2 AND CAP_CANCELADO IN ('Y', 'C', 'S')"
}

// VENDAS_POR_FAIXA_HORARIA
func (r *Rms511) VENDAS_POR_FAIXA_HORARIA() string {
	return "SELECT EXTRACT(HOUR FROM TO_TIMESTAMP(TO_CHAR(CAP_HORA_TRANSACAO, '000000'), 'HH24MISS')) AS HORA, SUM(DET_TOTAL) AS VALOR, COUNT(DISTINCT CAP_NR_CUPOM) AS CUPONS, COUNT(*) AS ITENS, ROUND(COUNT(*) / COUNT(DISTINCT CAP_NR_CUPOM), 2) AS MEDIA_ITENS, ROUND(SUM(DET_TOTAL) / COUNT(DISTINCT CAP_NR_CUPOM), 2) AS MEDIA_VALOR FROM RMS.CAPCUPOM JOIN RMS.DETCUPOM ON CAP_FILIAL = DET_FILIAL AND CAP_DATA = DET_DATA AND CAP_NR_CUPOM = DET_NR_CUPOM AND CAP_NR_PDV = DET_NR_PDV WHERE CAP_CANCELADO = 'N' AND DET_CANCELADO = 'N' AND CAP_DATA = :1 AND CAP_FILIAL = :2 GROUP BY EXTRACT(HOUR FROM TO_TIMESTAMP(TO_CHAR(CAP_HORA_TRANSACAO, '000000'), 'HH24MISS')) ORDER BY HORA"
}

// PRODUTOS_MAIS_VENDIDO_DIA
func (r *Rms511) PRODUTOS_MAIS_VENDIDO_DIA() string {
	return "SELECT * FROM (SELECT A.DET_EAN AS EAN, C.GIT_DESCRICAO AS DESCRICAO, ROUND(SUM(A.DET_TOTAL) / SUM(A.DET_QTDE), 2) AS VALOR_UNT, SUM(A.DET_QTDE) AS QTDE, SUM(A.DET_TOTAL) AS TOTAL FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV LEFT JOIN RMS.AA3CITEM C ON A.DET_EAN = C.GIT_CODIGO_EAN13 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND A.DET_CANCELADO = 'N' GROUP BY A.DET_EAN, C.GIT_DESCRICAO ORDER BY TOTAL DESC) WHERE ROWNUM <= 200"
}

// PRODUTOS_ESTATISTICA
func (r *Rms511) PRODUTOS_ESTATISTICA() string {
	return "SELECT * FROM (SELECT A.DET_EAN AS EAN, C.GIT_DESCRICAO AS DESCRICAO, ROUND(SUM(A.DET_TOTAL) / SUM(A.DET_QTDE), 2) AS VALOR_UNT, SUM(A.DET_QTDE) AS QTDE, SUM(A.DET_TOTAL) AS TOTAL FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV LEFT JOIN RMS.AA3CITEM C ON A.DET_EAN = C.GIT_CODIGO_EAN13 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND A.DET_CANCELADO = 'N' GROUP BY A.DET_EAN, C.GIT_DESCRICAO ORDER BY TOTAL DESC) WHERE ROWNUM <= 5000"
}

// TOTAL_VENDIDO_POR_MODALIDADES
func (r *Rms511) TOTAL_VENDIDO_POR_MODALIDADES() string {
	return "SELECT detp_cod_pgto AS CODIGO, detp_descr_pgto AS DESCRICAO, COUNT(*) AS QTDE, SUM(detp_vlr_pgto) - NVL(SUM(dett_vlr_troco), 0) AS TOTAL FROM rms.detcupomp1 LEFT JOIN rms.detcupomt1 ON detp_data = dett_data AND detp_filial = dett_filial AND detp_nr_cupom = dett_nr_cupom AND detp_nr_pdv = dett_nr_pdv WHERE detp_filial = :2 AND detp_data = :1 AND detp_cancelado = 'N' GROUP BY detp_cod_pgto, detp_descr_pgto ORDER BY TOTAL DESC"
}

// ESTORNO_DE_CUPONS_POR_OPERADOR_DIA
func (r *Rms511) ESTORNO_DE_CUPONS_POR_OPERADOR_DIA() string {
	return "SELECT pdvcc_cxa AS PDV, pdvcc_dta AS DATA, pdvcc_hrs_emi AS HORA, tip_razao_social AS OPER, NULL, pdvcc_ctb_val AS VALOR, pdvcc_cup AS CUPOM FROM rms.ag1pdvcc JOIN rms.aa2ctipo ON tip_codigo = pdvcc_ope WHERE pdvcc_sit = 'C' AND pdvcc_dta = :1 AND pdvcc_loj = :2"
}

// DESCONTOS_DE_ITENS_DIA
func (r *Rms511) DESCONTOS_DE_ITENS_DIA() string {
	return "SELECT pdvcc_dta_emi AS DATA, pdvcc_hrs_emi AS HORA, tip_razao_social AS OPERADOR, NULL, pdvci_dsc_val AS DESCONTO, pdvcc_cup AS CUPOM, pdvci_seq AS SEQ, pdvci_ean AS EAN, git_descricao AS DESCRICAO FROM rms.ag1pdvci JOIN rms.ag1pdvcc ON pdvcc_id = pdvci_id JOIN rms.aa3citem ON git_cod_item = pdvci_ite JOIN rms.aa2ctipo ON tip_codigo = pdvcc_ope WHERE pdvci_dsc_val <> 0 AND pdvcc_dta = :1 AND pdvcc_loj = :2"
}

// VENDAS_POR_SECOES_DIA
func (r *Rms511) VENDAS_POR_SECOES_DIA() string {
	return "SELECT NVL(TO_CHAR(A.DET_COD_ITEM), '0') AS CODIGO, NVL(B.NCC_DESCRICAO, 'SEÇÃO DESCONHECIDA') AS DESCRICAO, SUM(A.DET_QTDE) AS QUANTIDADE, SUM(A.DET_TOTAL) AS VALOR FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM C ON A.DET_FILIAL = C.CAP_FILIAL AND A.DET_DATA = C.CAP_DATA AND A.DET_NR_CUPOM = C.CAP_NR_CUPOM AND A.DET_NR_PDV = C.CAP_NR_PDV LEFT JOIN RMS.AA3CNVCC B ON A.DET_COD_ITEM = B.NCC_SECAO AND B.NCC_GRUPO = 0 AND B.NCC_SUBGRUPO = 0 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND C.CAP_TIPO_TRANSACAO = 1 AND C.CAP_CANCELADO = 'N' GROUP BY NVL(TO_CHAR(A.DET_COD_ITEM), '0'), NVL(B.NCC_DESCRICAO, 'SEÇÃO DESCONHECIDA') ORDER BY VALOR DESC"
}

// TOTAL_CUPONS_POR_OPERADOR_DIA
func (r *Rms511) TOTAL_CUPONS_POR_OPERADOR_DIA() string {
	return "SELECT COUNT(*) AS CUPONS, C.TIP_NOME_FANTASIA AS OPERADOR, SUM(B.CAP_VLR_CUPOM) AS VALOR FROM RMS.CAPCUPOM B JOIN RMS.AA2CTIPO C ON B.CAP_COD_OPERADOR = C.TIP_CODIGO WHERE B.CAP_CANCELADO = 'N' AND B.CAP_DATA = :1 AND B.CAP_FILIAL = :2 GROUP BY C.TIP_NOME_FANTASIA ORDER BY CUPONS DESC"
}

// VENDAS_POR_VENDEDOR_DIA
func (r *Rms511) VENDAS_POR_VENDEDOR_DIA() string {
	return "SELECT C.CAP_DATA AS DATA, V.TIP_NOME_FANTASIA AS VENDEDOR, SUM(D.DET_TOTAL) AS VALOR, COUNT(DISTINCT C.CAP_NR_CUPOM) AS CUPONS, COUNT(D.DET_SEQ) AS ITENS, ROUND(COUNT(D.DET_SEQ) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_ITENS, ROUND(SUM(D.DET_TOTAL) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_VALOR FROM RMS.CAPCUPOM C JOIN RMS.AA2CTIPO V ON C.CAP_COD_OPERADOR = V.TIP_CODIGO JOIN RMS.DETCUPOM D ON C.CAP_FILIAL = D.DET_FILIAL AND C.CAP_DATA = D.DET_DATA AND C.CAP_NR_CUPOM = D.DET_NR_CUPOM WHERE C.CAP_CANCELADO = 'N' AND C.CAP_DATA = :1 AND C.CAP_FILIAL = :2 GROUP BY C.CAP_DATA, V.TIP_NOME_FANTASIA ORDER BY VALOR DESC"
}

// MODALIDADES_PAGAMENTO_OPERADOR_DIA
func (r *Rms511) MODALIDADES_PAGAMENTO_OPERADOR_DIA() string {
	return "SELECT detp_data AS DATA, tip_razao_social AS OPERADOR, detp_cod_pgto AS CODIGO, detp_descr_pgto AS DESCRICAO, COUNT(*) AS QTDE, SUM(detp_vlr_pgto) - NVL(SUM(dett_vlr_troco), 0) AS TOTAL FROM rms.detcupomp1 JOIN rms.ag1pdvcc ON detp_data = pdvcc_dta AND detp_nr_pdv = pdvcc_cxa AND detp_filial = pdvcc_loj AND detp_nr_cupom = pdvcc_cup JOIN rms.aa2ctipo ON pdvcc_ope = tip_codigo LEFT JOIN rms.detcupomt1 ON detp_data = dett_data AND detp_filial = dett_filial AND detp_nr_cupom = dett_nr_cupom AND dett_nr_pdv = dett_nr_pdv WHERE detp_filial = :2 AND detp_data = :1 AND detp_cancelado = 'N' GROUP BY detp_data, tip_razao_social, detp_cod_pgto, detp_descr_pgto"
}
