package rms

type Rms512 struct{}

func (r *Rms512) TOTAL_VENDIDO_DIA() string {
	return `SELECT COALESCE(SUM(A.DET_TOTAL), 0) AS VALOR_TOTAL, COALESCE(SUM(A.DET_VLR_ICMS), 0) AS ICMS_TOTAL, COALESCE(SUM(A.DET_TOTAL - A.DET_VLR_ICMS), 0) AS LUCRO_TOTAL FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND B.CAP_CANCELADO = 'N'`
}

func (r *Rms512) TICKET_MEDIO_DIA() string {
	return `SELECT ROUND(SUM(B.CAP_VLR_CUPOM) / COUNT(*), 2) AS TICKET_MEDIO FROM RMS.CAPCUPOM B WHERE B.CAP_DATA = :1 AND B.CAP_FILIAL = :2 AND B.CAP_CANCELADO = 'N'`
}

func (r *Rms512) PRODUTOS_POR_ATENDIMENTO_DIA() string {
	return `SELECT ROUND(COUNT(A.DET_EAN) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_PRODUTOS FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM C ON A.DET_FILIAL = C.CAP_FILIAL AND A.DET_DATA = C.CAP_DATA AND A.DET_NR_CUPOM = C.CAP_NR_CUPOM AND A.DET_NR_PDV = C.CAP_NR_PDV WHERE A.DET_CANCELADO = 'N' AND C.CAP_CANCELADO = 'N' AND A.DET_DATA = :1 AND A.DET_FILIAL = :2`
}

func (r *Rms512) TOTAL_CUPONS_VALIDOS_DIA() string {
	return `SELECT COUNT(*) AS TOTAL_CUPONS FROM RMS.CAPCUPOM WHERE CAP_DATA = :1 AND CAP_FILIAL = :2 AND CAP_CANCELADO = 'N'`
}

func (r *Rms512) TOTAL_CUPONS_CANCELADOS_DIA() string {
	return `SELECT COUNT(*) AS TOTAL_CUPONS_CANCELADOS FROM RMS.CAPCUPOM WHERE CAP_DATA = :1 AND CAP_FILIAL = :2 AND CAP_CANCELADO IN ('Y', 'C', 'S')`
}

func (r *Rms512) VENDAS_POR_FAIXA_HORARIA() string {
	return `SELECT EXTRACT(HOUR FROM TO_TIMESTAMP(TO_CHAR(C.CAP_HORA_TRANSACAO, '000000'), 'HH24MISS')) AS HORA, SUM(A.DET_TOTAL) AS VALOR_TOTAL, COUNT(DISTINCT C.CAP_NR_CUPOM) AS TOTAL_CUPONS, COUNT(A.DET_SEQ) AS TOTAL_ITENS, ROUND(COUNT(A.DET_SEQ) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_ITENS_POR_CUPOM, ROUND(SUM(A.DET_TOTAL) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_VALOR_POR_CUPOM FROM RMS.CAPCUPOM C JOIN RMS.DETCUPOM A ON C.CAP_FILIAL = A.DET_FILIAL AND C.CAP_DATA = A.DET_DATA AND C.CAP_NR_CUPOM = A.DET_NR_CUPOM AND C.CAP_NR_PDV = A.DET_NR_PDV WHERE C.CAP_CANCELADO = 'N' AND A.DET_CANCELADO = 'N' AND C.CAP_DATA = :1 AND C.CAP_FILIAL = :2 GROUP BY EXTRACT(HOUR FROM TO_TIMESTAMP(TO_CHAR(C.CAP_HORA_TRANSACAO, '000000'), 'HH24MISS')) ORDER BY HORA`
}

func (r *Rms512) PRODUTOS_MAIS_VENDIDO_DIA() string {
	return `SELECT * FROM (SELECT A.DET_EAN AS EAN, COALESCE(C.GIT_DESCRICAO, 'DESCONHECIDO') AS DESCRICAO, ROUND(SUM(A.DET_TOTAL) / SUM(A.DET_QTDE), 2) AS VALOR_UNITARIO, SUM(A.DET_QTDE) AS QUANTIDADE, SUM(A.DET_TOTAL) AS TOTAL, COALESCE(SUM(A.DET_VLR_ICMS), 0) AS CUSTO, SUM(A.DET_TOTAL - A.DET_VLR_ICMS) AS LUCRO FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV LEFT JOIN RMS.AA3CITEM C ON A.DET_EAN = C.GIT_CODIGO_EAN13 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND A.DET_CANCELADO = 'N' GROUP BY A.DET_EAN, C.GIT_DESCRICAO ORDER BY TOTAL DESC) WHERE ROWNUM <= 200`
}

func (r *Rms512) PRODUTOS_ESTATISTICA() string {
	return `SELECT * FROM (SELECT A.DET_EAN AS EAN, COALESCE(C.GIT_DESCRICAO, 'DESCONHECIDO') AS DESCRICAO, ROUND(SUM(A.DET_TOTAL) / SUM(A.DET_QTDE), 2) AS VALOR_UNITARIO, SUM(A.DET_QTDE) AS QUANTIDADE, SUM(A.DET_TOTAL) AS TOTAL, SUM(A.DET_TOTAL - A.DET_VLR_ICMS) AS CUSTO, SUM(A.DET_TOTAL - (A.DET_TOTAL - A.DET_VLR_ICMS)) AS LUCRO FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM B ON A.DET_FILIAL = B.CAP_FILIAL AND A.DET_DATA = B.CAP_DATA AND A.DET_NR_CUPOM = B.CAP_NR_CUPOM AND A.DET_NR_PDV = B.CAP_NR_PDV LEFT JOIN RMS.AA3CITEM C ON A.DET_EAN = C.GIT_CODIGO_EAN13 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND B.CAP_TIPO_TRANSACAO = 1 AND A.DET_CANCELADO = 'N' GROUP BY A.DET_EAN, C.GIT_DESCRICAO ORDER BY TOTAL DESC) WHERE ROWNUM <= 5000`
}

func (r *Rms512) TOTAL_VENDIDO_POR_MODALIDADES() string {
	return `SELECT DETP_COD_PGTO AS CODIGO, DETP_DESCR_PGTO AS DESCRICAO, COUNT(*) AS QTDE, SUM(DETP_VLR_PGTO) - NVL(SUM(DETT_VLR_TROCO), 0) AS TOTAL FROM RMS.DETCUPOMP1 LEFT JOIN RMS.DETCUPOMT1 ON DETP_DATA = DETT_DATA AND DETP_FILIAL = DETT_FILIAL AND DETP_NR_CUPOM = DETT_NR_CUPOM AND DETP_NR_PDV = DETT_NR_PDV WHERE DETP_FILIAL = :2 AND DETP_DATA = :1 AND DETP_CANCELADO = 'N' GROUP BY DETP_COD_PGTO, DETP_DESCR_PGTO ORDER BY TOTAL DESC`
}

func (r *Rms512) ESTORNO_DE_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT PDVCC_CXA AS PDV, PDVCC_DTA AS DATA, PDVCC_HRS_EMI AS HORA, TIP_RAZAO_SOCIAL AS OPERADOR, NULL AS SUPERVISOR, PDVCC_CTB_VAL AS VALOR, PDVCC_CUP AS CUPOM FROM RMS.AG1PDVCC JOIN RMS.AA2CTIPO ON TIP_CODIGO = PDVCC_OPE WHERE PDVCC_SIT = 'C' AND PDVCC_DTA = :1 AND PDVCC_LOJ = :2`
}

func (r *Rms512) DESCONTOS_DE_ITENS_DIA() string {
	return `SELECT PDVCC_DTA_EMI AS DATA, PDVCC_HRS_EMI AS HORA, TIP_RAZAO_SOCIAL AS OPERADOR, NULL AS SUPERVISOR, PDVCI_DSC_VAL AS DESCONTO, PDVCC_CUP AS CUPOM, PDVCI_SEQ AS SEQ, PDVCI_EAN AS EAN, GIT_DESCRICAO AS DESCRICAO_PRODUTO FROM RMS.AG1PDVCI JOIN RMS.AG1PDVCC ON PDVCC_ID = PDVCI_ID JOIN RMS.AA3CITEM ON GIT_COD_ITEM = PDVCI_ITE JOIN RMS.AA2CTIPO ON TIP_CODIGO = PDVCC_OPE WHERE PDVCI_DSC_VAL <> 0 AND PDVCC_DTA = :1 AND PDVCC_LOJ = :2`
}

func (r *Rms512) VENDAS_POR_SECOES_DIA() string {
	return `SELECT NVL(TO_CHAR(B.NCC_SECAO), 'DESCONHECIDO') AS CODIGO_SECAO, NVL(B.NCC_DESCRICAO, 'SEÇÃO DESCONHECIDA') AS DESCRICAO_SECAO, SUM(A.DET_QTDE) AS QUANTIDADE, SUM(A.DET_TOTAL) AS VALOR FROM RMS.DETCUPOM A JOIN RMS.CAPCUPOM C ON A.DET_FILIAL = C.CAP_FILIAL AND A.DET_DATA = C.CAP_DATA AND A.DET_NR_CUPOM = C.CAP_NR_CUPOM AND A.DET_NR_PDV = C.CAP_NR_PDV LEFT JOIN RMS.AA3CNVCC B ON TO_NUMBER(A.DET_COD_ITEM) = TO_NUMBER(B.NCC_SECAO) AND B.NCC_GRUPO = 0 AND B.NCC_SUBGRUPO = 0 WHERE A.DET_DATA = :1 AND A.DET_FILIAL = :2 AND C.CAP_TIPO_TRANSACAO = 1 AND C.CAP_CANCELADO = 'N' GROUP BY NVL(TO_CHAR(B.NCC_SECAO), 'DESCONHECIDO'), NVL(B.NCC_DESCRICAO, 'SEÇÃO DESCONHECIDA') ORDER BY VALOR DESC`
}

func (r *Rms512) TOTAL_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT COUNT(*) AS CUPONS, C.TIP_NOME_FANTASIA AS OPERADOR, SUM(B.CAP_VLR_CUPOM) AS VALOR FROM RMS.CAPCUPOM B JOIN RMS.AA2CTIPO C ON B.CAP_COD_OPERADOR = C.TIP_CODIGO WHERE B.CAP_CANCELADO = 'N' AND B.CAP_DATA = :1 AND B.CAP_FILIAL = :2 GROUP BY C.TIP_NOME_FANTASIA ORDER BY CUPONS DESC`
}

func (r *Rms512) VENDAS_POR_VENDEDOR_DIA() string {
	return `SELECT C.CAP_DATA AS DATA, V.TIP_NOME_FANTASIA AS VENDEDOR, SUM(D.DET_TOTAL) AS VALOR, COUNT(DISTINCT C.CAP_NR_CUPOM) AS CUPONS, COUNT(D.DET_SEQ) AS ITENS, ROUND(COUNT(D.DET_SEQ) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_ITENS, ROUND(SUM(D.DET_TOTAL) / COUNT(DISTINCT C.CAP_NR_CUPOM), 2) AS MEDIA_VALOR FROM RMS.CAPCUPOM C JOIN RMS.AA2CTIPO V ON C.CAP_COD_OPERADOR = V.TIP_CODIGO JOIN RMS.DETCUPOM D ON C.CAP_FILIAL = D.DET_FILIAL AND C.CAP_DATA = D.DET_DATA AND C.CAP_NR_CUPOM = D.DET_NR_CUPOM WHERE C.CAP_CANCELADO = 'N' AND C.CAP_DATA = :1 AND C.CAP_FILIAL = :2 GROUP BY C.CAP_DATA, V.TIP_NOME_FANTASIA ORDER BY VALOR DESC`
}

func (r *Rms512) MODALIDADES_PAGAMENTO_OPERADOR_DIA() string {
	return `SELECT A.DETP_DATA AS DATA, C.TIP_NOME_FANTASIA AS OPERADOR, A.DETP_COD_PGTO AS CODIGO, A.DETP_DESCR_PGTO AS DESCRICAO, COUNT(*) AS QTDE, SUM(A.DETP_VLR_PGTO) - NVL(SUM(B.DETT_VLR_TROCO), 0) AS TOTAL FROM RMS.DETCUPOMP1 A LEFT JOIN RMS.DETCUPOMT1 B ON A.DETP_DATA = B.DETT_DATA AND A.DETP_FILIAL = B.DETT_FILIAL AND A.DETP_NR_CUPOM = B.DETT_NR_CUPOM AND A.DETP_NR_PDV = B.DETT_NR_PDV JOIN RMS.CAPCUPOM D ON A.DETP_FILIAL = D.CAP_FILIAL AND A.DETP_DATA = D.CAP_DATA AND A.DETP_NR_PDV = D.CAP_NR_PDV AND A.DETP_NR_CUPOM = D.CAP_NR_CUPOM JOIN RMS.AA2CTIPO C ON D.CAP_COD_OPERADOR = C.TIP_CODIGO WHERE A.DETP_FILIAL = :2 AND A.DETP_DATA = :1 AND A.DETP_CANCELADO = 'N' GROUP BY A.DETP_DATA, C.TIP_NOME_FANTASIA, A.DETP_COD_PGTO, A.DETP_DESCR_PGTO ORDER BY TOTAL DESC`
}
