# Generated by Django 4.2.7 on 2023-11-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_funeraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planofunerario',
            name='nome',
            field=models.CharField(default='Nome padrão', max_length=255),
        ),
    ]
