package concinco

type Concinco281 struct{}

// 1. TOTAL_VENDIDO_DIA
func (c *Concinco281) TOTAL_VENDIDO_DIA() string {
	return `SELECT 
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS VALOR,
    ROUND(COALESCE(SUM(y.CMDIAVLRNF * v.QTDITEM), 0), 2) AS CUSTO,
    ROUND(COALESCE(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 0), 2) AS LUCRO
FROM MAXV_ABCDISTRIBBASE v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA  
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON v.SEQPRODUTO = a.SEQPRODUTO
INNER JOIN MAX_EMPRESA e ON e.NROEMPRESA = v.NROEMPRESA
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 2. TICKET_MEDIO_DIA
func (c *Concinco281) TICKET_MEDIO_DIA() string {
	return `SELECT 
    ROUND(COALESCE(AVG(cupom_total.VALOR), 0), 2) AS TICKET_MEDIO
FROM (
    SELECT 
        v.ROWIDDOCTO,
        COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0) AS VALOR
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    GROUP BY v.ROWIDDOCTO
) cupom_total`
}

// 3. PRODUTOS_POR_ATENDIMENTO_DIA
func (c *Concinco281) PRODUTOS_POR_ATENDIMENTO_DIA() string {
	return `SELECT 
    ROUND(COALESCE(AVG(cupom_itens.QTDITEM), 0), 2) AS MEDIA_ITENS
FROM (
    SELECT 
        v.ROWIDDOCTO,
        COALESCE(SUM(v.QTDITEM), 0) AS QTDITEM
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    GROUP BY v.ROWIDDOCTO
) cupom_itens`
}

// 4. TOTAL_CUPONS_VALIDOS_DIA
func (c *Concinco281) TOTAL_CUPONS_VALIDOS_DIA() string {
	return `SELECT 
    COALESCE(COUNT(DISTINCT v.ROWIDDOCTO), 0) AS CUPONS_VALIDOS
FROM MAXV_ABCDISTRIBBASE v
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 5. TOTAL_CUPONS_CANCELADOS_DIA
func (c *Concinco281) TOTAL_CUPONS_CANCELADOS_DIA() string {
	return `SELECT 
    COALESCE(COUNT(*), 0) AS CUPONS_CANCELADOS
FROM MFL_DOCTOFISCAL df
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'C'
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )`
}

// 6. VENDAS_POR_FAIXA_HORARIA
func (c *Concinco281) VENDAS_POR_FAIXA_HORARIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(v.dtahorlancto, 'HH24'), '00') AS HORA,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS VALOR,
    COALESCE(COUNT(DISTINCT v.ROWIDDOCTO), 0) AS NUM_CUPONS,
    ROUND(COALESCE(SUM(v.QTDITEM), 0), 0) AS NUM_ITENS,
    ROUND(COALESCE(SUM(v.QTDITEM) / NULLIF(COUNT(DISTINCT v.ROWIDDOCTO), 0), 0), 2) AS MEDIA_ITENS,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM) / NULLIF(COUNT(DISTINCT v.ROWIDDOCTO), 0), 0), 2) AS MEDIA_VALOR
FROM MAXV_ABCDISTRIBBASE v
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY TO_CHAR(v.dtahorlancto, 'HH24')
ORDER BY 1`
}

// 7. PRODUTOS_MAIS_VENDIDO_DIA
func (c *Concinco281) PRODUTOS_MAIS_VENDIDO_DIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(a.SEQPRODUTO), '0') AS EAN,
    COALESCE(a.DESCCOMPLETA, 'SEM DESCRIÇÃO') AS DESCRICAO,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM) / NULLIF(SUM(v.QTDITEM), 0), 0), 2) AS VALOR_UNITARIO,
    COALESCE(SUM(v.QTDITEM), 0) AS QUANTIDADE,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS TOTAL,
    ROUND(COALESCE(SUM(y.CMDIAVLRNF * v.QTDITEM), 0), 2) AS CUSTO,
    ROUND(COALESCE(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 0), 2) AS LUCRO
FROM (
    SELECT 
        v.SEQPRODUTO,
        COALESCE(v.VLRITEM, 0) AS VLRITEM,
        COALESCE(v.VLRDEVOLITEM, 0) AS VLRDEVOLITEM,
        COALESCE(v.QTDITEM, 0) AS QTDITEM,
        v.SEQPRODUTOCUSTO,
        v.DTAVDA,
        v.NROEMPRESA,
        ROWNUM as rn
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    ORDER BY v.VLRITEM - v.VLRDEVOLITEM DESC
) v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
WHERE v.rn <= 200
GROUP BY a.SEQPRODUTO, a.DESCCOMPLETA
ORDER BY SUM(v.VLRITEM - v.VLRDEVOLITEM) DESC`
}

// 8. PRODUTOS_ESTATISTICA
func (c *Concinco281) PRODUTOS_ESTATISTICA() string {
	return `SELECT 
    COALESCE(TO_CHAR(a.SEQPRODUTO), '0') AS EAN,
    COALESCE(a.DESCCOMPLETA, 'SEM DESCRIÇÃO') AS DESCRICAO,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM) / NULLIF(SUM(v.QTDITEM), 0), 0), 2) AS VALOR_UNITARIO,
    COALESCE(SUM(v.QTDITEM), 0) AS QUANTIDADE,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS TOTAL,
    ROUND(COALESCE(SUM(y.CMDIAVLRNF * v.QTDITEM), 0), 2) AS CUSTO,
    ROUND(COALESCE(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 0), 2) AS LUCRO
FROM (
    SELECT 
        v.SEQPRODUTO,
        COALESCE(v.VLRITEM, 0) AS VLRITEM,
        COALESCE(v.VLRDEVOLITEM, 0) AS VLRDEVOLITEM,
        COALESCE(v.QTDITEM, 0) AS QTDITEM,
        v.SEQPRODUTOCUSTO,
        v.DTAVDA,
        v.NROEMPRESA,
        ROWNUM as rn
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    ORDER BY v.VLRITEM - v.VLRDEVOLITEM DESC
) v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
WHERE v.rn <= 5000
GROUP BY a.SEQPRODUTO, a.DESCCOMPLETA
ORDER BY SUM(v.VLRITEM - v.VLRDEVOLITEM) DESC`
}

// 9. TOTAL_VENDIDO_POR_MODALIDADES
func (c *Concinco281) TOTAL_VENDIDO_POR_MODALIDADES() string {
	return `SELECT 
    COALESCE(fp.NROFORMAPAGTO, 0) AS CODIGO,
    COALESCE(fp.FORMAPAGTO, 'MODALIDADE DESCONHECIDA') AS DESCRICAO,
    COALESCE(COUNT(DISTINCT v.ROWIDDOCTO), 0) AS QUANTIDADE,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS TOTAL
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MRL_FORMAPAGTO fp ON fp.NROFORMAPAGTO = v.NROFORMAPAGTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY fp.NROFORMAPAGTO, fp.FORMAPAGTO
ORDER BY TOTAL DESC`
}

// 10. ESTORNO_DE_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) ESTORNO_DE_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(df.NROECF), '0') AS PDV,
    COALESCE(TO_CHAR(df.DTAHOREMISSAO, 'DD/MM/YYYY'), '01/01/1900') AS DATA,
    COALESCE(TO_CHAR(df.DTAHOREMISSAO, 'HH24:MI:SS'), '00:00:00') AS HORA,
    COALESCE(u.NOME, 'OPERADOR DESCONHECIDO') AS OPERADOR,
    COALESCE(df.USUCANCELOU, 'SEM SUPERVISOR') AS SUPERVISOR,
    ROUND(COALESCE(SUM(i.VLRITEM), 0), 2) AS VALOR,
    COALESCE(TO_CHAR(df.NUMERODF), '0') AS CUPOM
FROM MFL_DOCTOFISCAL df
INNER JOIN MFL_DFITEM i ON (
    df.NUMERODF = i.NUMERODF
    AND df.NROEMPRESA = i.NROEMPRESA
    AND df.SERIEDF = i.SERIEDF
    AND df.SEQNF = i.SEQNF
)
LEFT JOIN GE_USUARIO u ON u.SEQUSUARIO = df.SEQOPERADOR
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'C'
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )
GROUP BY df.NROECF, df.DTAHOREMISSAO, df.DTAHOREMISSAO, u.NOME, df.USUCANCELOU, df.NUMERODF
ORDER BY DATA, HORA`
}

// 11. DESCONTOS_DE_ITENS_DIA
func (c *Concinco281) DESCONTOS_DE_ITENS_DIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(df.DTAHOREMISSAO, 'DD/MM/YYYY'), '01/01/1900') AS DATA,
    COALESCE(TO_CHAR(df.DTAHOREMISSAO, 'HH24:MI:SS'), '00:00:00') AS HORA,
    COALESCE(u.NOME, 'OPERADOR DESCONHECIDO') AS OPERADOR,
    COALESCE(df.USUCANCELOU, 'SEM SUPERVISOR') AS SUPERVISOR,
    ROUND(COALESCE(SUM(i.VLRDESCONTO), 0), 2) AS VALOR,
    COALESCE(TO_CHAR(i.NUMERODF), '0') AS CUPOM,
    COALESCE(TO_CHAR(i.SEQPRODUTO), '0') AS ITEM,
    COALESCE(TO_CHAR(i.CODPRODUTO), '0') AS EAN,
    COALESCE(p.DESCCOMPLETA, 'SEM DESCRIÇÃO') AS DESCRICAO
FROM MFL_DOCTOFISCAL df
INNER JOIN MFL_DFITEM i ON (
    df.NUMERODF = i.NUMERODF
    AND df.NROEMPRESA = i.NROEMPRESA
    AND df.SERIEDF = i.SERIEDF
    AND df.SEQNF = i.SEQNF
)
INNER JOIN MAP_PRODUTO p ON i.SEQPRODUTO = p.SEQPRODUTO
LEFT JOIN GE_USUARIO u ON u.SEQUSUARIO = df.SEQOPERADOR
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'V'
  AND i.STATUSITEM = 'V'
  AND i.VLRDESCONTO > 0
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )
GROUP BY 
    df.DTAHOREMISSAO,
    u.NOME,
    df.USUCANCELOU,
    i.NUMERODF,
    i.SEQPRODUTO,
    i.CODPRODUTO,
    p.DESCCOMPLETA
ORDER BY DATA, HORA, VALOR DESC`
}

// 12. VENDAS_POR_SECOES_DIA
func (c *Concinco281) VENDAS_POR_SECOES_DIA() string {
	return `WITH produtos_categoria AS (
    SELECT DISTINCT
        v.SEQPRODUTO,
        FIRST_VALUE(COALESCE(cat.SEQCATEGORIA, 0)) OVER (
            PARTITION BY v.SEQPRODUTO 
            ORDER BY cat.SEQCATEGORIA
        ) AS SEQCATEGORIA_N2,
        FIRST_VALUE(COALESCE(cat.CATEGORIA, 'SEM CATEGORIA')) OVER (
            PARTITION BY v.SEQPRODUTO 
            ORDER BY cat.SEQCATEGORIA
        ) AS CATEGORIA_N2
    FROM MAXV_ABCDISTRIBBASE v
    INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
    LEFT JOIN MAP_FAMDIVISAO d ON d.SEQFAMILIA = a.SEQFAMILIA
    LEFT JOIN MAP_FAMDIVCATEG u ON (
        u.SEQFAMILIA = d.SEQFAMILIA
        AND u.NRODIVISAO = d.NRODIVISAO
    )
    LEFT JOIN MAXV_CATEGORIA cat ON (
        cat.SEQCATEGORIA = u.SEQCATEGORIA
        AND cat.NRODIVISAO = u.NRODIVISAO
        AND cat.NIVELHIERARQUIA = 2
        AND cat.STATUSCATEGOR != 'I'
        AND cat.TIPCATEGORIA = 'M'
    )
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
)
SELECT 
    COALESCE(pc.SEQCATEGORIA_N2, 0) AS CODIGO,
    COALESCE(pc.CATEGORIA_N2, 'SEM CATEGORIA NIVEL 2') AS DESCRICAO,
    ROUND(COALESCE(SUM(v.QTDITEM), 0), 2) AS QUANTIDADE,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS VALOR,
    ROUND(COALESCE(SUM(y.CMDIAVLRNF * v.QTDITEM), 0), 2) AS CUSTO,
    ROUND(COALESCE(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 0), 2) AS LUCRO
FROM MAXV_ABCDISTRIBBASE v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
LEFT JOIN produtos_categoria pc ON pc.SEQPRODUTO = v.SEQPRODUTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY pc.SEQCATEGORIA_N2, pc.CATEGORIA_N2
ORDER BY VALOR DESC`
}

// 13. TOTAL_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) TOTAL_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    COALESCE(COUNT(DISTINCT cupom_valor.ROWIDDOCTO), 0) AS QTD_CUPONS,
    cupom_valor.OPERADOR,
    ROUND(COALESCE(SUM(cupom_valor.VALOR), 0), 2) AS VALOR
FROM (
    SELECT DISTINCT
        v.ROWIDDOCTO,
        COALESCE(TRIM(v.OPERADOR), 'OPERADOR SEM DESCRIÇÃO') AS OPERADOR,
        COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM) OVER (PARTITION BY v.ROWIDDOCTO), 0) AS VALOR
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
) cupom_valor
GROUP BY cupom_valor.OPERADOR
ORDER BY QTD_CUPONS DESC`
}

// 14. VENDAS_POR_VENDEDOR_DIA
func (c *Concinco281) VENDAS_POR_VENDEDOR_DIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(v.DTAVDA, 'DD/MM/YYYY'), '01/01/1900') AS DATA,
    COALESCE(j.APELIDO, 'SEM VENDEDOR') AS VENDEDOR,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS VALOR,
    COALESCE(COUNT(DISTINCT v.ROWIDDOCTO), 0) AS CUPONS,
    ROUND(COALESCE(SUM(v.QTDITEM), 0), 0) AS ITEM,
    ROUND(COALESCE(SUM(v.QTDITEM) / NULLIF(COUNT(DISTINCT v.ROWIDDOCTO), 0), 0), 2) AS MEDIA_ITENS,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM) / NULLIF(COUNT(DISTINCT v.ROWIDDOCTO), 0), 0), 2) AS MEDIA_VALOR
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MAD_REPRESENTANTE j ON j.NROREPRESENTANTE = v.NROREPRESENTANTE
LEFT JOIN GE_PESSOA rpe ON rpe.SEQPESSOA = j.SEQPESSOA
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY v.DTAVDA, j.APELIDO
ORDER BY VALOR DESC`
}

// 15. MODALIDADES_PAGAMENTO_OPERADOR_DIA
func (c *Concinco281) MODALIDADES_PAGAMENTO_OPERADOR_DIA() string {
	return `SELECT 
    COALESCE(TO_CHAR(v.DTAVDA, 'DD/MM/YYYY'), '01/01/1900') AS DATA,
    COALESCE(TRIM(v.OPERADOR), 'OPERADOR DESCONHECIDO') AS OPERADOR,
    COALESCE(fp.NROFORMAPAGTO, 0) AS COD_PAGTO,
    COALESCE(fp.FORMAPAGTO, 'MODALIDADE SEM DESCRIÇÃO') AS DESCRICAO,
    COALESCE(COUNT(DISTINCT v.ROWIDDOCTO), 0) AS QTD,
    ROUND(COALESCE(SUM(v.VLRITEM - v.VLRDEVOLITEM), 0), 2) AS VALOR
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MRL_FORMAPAGTO fp ON fp.NROFORMAPAGTO = v.NROFORMAPAGTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY 
    v.DTAVDA,
    v.OPERADOR,
    fp.NROFORMAPAGTO,
    fp.FORMAPAGTO
ORDER BY DATA, OPERADOR, COD_PAGTO`
}
