package concinco

type Concinco281 struct{}

// 1. TOTAL_VENDIDO_DIA
func (c *Concinco281) TOTAL_VENDIDO_DIA() string {
	return `SELECT 
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS VALOR,
    ROUND(SUM(y.CMDIAVLRNF * v.QTDITEM), 2) AS CUSTO,
    ROUND(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 2) AS LUCRO
FROM MAXV_ABCDISTRIBBASE v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA  
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON v.SEQPRODUTO = a.SEQPRODUTO
INNER JOIN MAX_EMPRESA e ON e.NROEMPRESA = v.NROEMPRESA
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 2. TICKET_MEDIO_DIA
func (c *Concinco281) TICKET_MEDIO_DIA() string {
	return `SELECT 
    ROUND(AVG(cupom_total.VALOR), 2) AS TICKET_MEDIO
FROM (
    SELECT 
        v.ROWIDDOCTO,
        SUM(v.VLRITEM - v.VLRDEVOLITEM) AS VALOR
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    GROUP BY v.ROWIDDOCTO
) cupom_total`
}

// 3. PRODUTOS_POR_ATENDIMENTO_DIA
func (c *Concinco281) PRODUTOS_POR_ATENDIMENTO_DIA() string {
	return `SELECT 
    ROUND(AVG(cupom_itens.QTDITEM), 2) AS MEDIA_ITENS
FROM (
    SELECT 
        v.ROWIDDOCTO,
        SUM(v.QTDITEM) AS QTDITEM
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    GROUP BY v.ROWIDDOCTO
) cupom_itens`
}

// 4. TOTAL_CUPONS_VALIDOS_DIA
func (c *Concinco281) TOTAL_CUPONS_VALIDOS_DIA() string {
	return `SELECT 
    COUNT(DISTINCT v.ROWIDDOCTO) AS CUPONS_VALIDOS
FROM MAXV_ABCDISTRIBBASE v
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 5. TOTAL_CUPONS_CANCELADOS_DIA
func (c *Concinco281) TOTAL_CUPONS_CANCELADOS_DIA() string {
	return `SELECT 
    COUNT(*) AS CUPONS_CANCELADOS
FROM MFL_DOCTOFISCAL df
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'C'
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )`
}

// 6. VENDAS_POR_FAIXA_HORARIA
func (c *Concinco281) VENDAS_POR_FAIXA_HORARIA() string {
	return `SELECT 
    TO_CHAR(v.dtahorlancto, 'HH24') AS HORA,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS VALOR,
    COUNT(DISTINCT v.ROWIDDOCTO) AS NUM_CUPONS,
    ROUND(SUM(v.QTDITEM), 0) AS NUM_ITENS,
    ROUND(SUM(v.QTDITEM) / COUNT(DISTINCT v.ROWIDDOCTO), 2) AS MEDIA_ITENS,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM) / COUNT(DISTINCT v.ROWIDDOCTO), 2) AS MEDIA_VALOR
FROM MAXV_ABCDISTRIBBASE v
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY TO_CHAR(v.dtahorlancto, 'HH24')
ORDER BY 1`
}

// 7. PRODUTOS_MAIS_VENDIDO_DIA
func (c *Concinco281) PRODUTOS_MAIS_VENDIDO_DIA() string {
	return `SELECT 
    a.SEQPRODUTO AS EAN,
    a.DESCCOMPLETA AS DESCRICAO,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM) / SUM(v.QTDITEM), 2) AS VALOR_UNITARIO,
    SUM(v.QTDITEM) AS QUANTIDADE,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS TOTAL,
    ROUND(SUM(y.CMDIAVLRNF * v.QTDITEM), 2) AS CUSTO,
    ROUND(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 2) AS LUCRO
FROM (
    SELECT 
        v.SEQPRODUTO,
        v.VLRITEM,
        v.VLRDEVOLITEM,
        v.QTDITEM,
        v.SEQPRODUTOCUSTO,
        v.DTAVDA,
        v.NROEMPRESA,
        ROWNUM as rn
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    ORDER BY v.VLRITEM - v.VLRDEVOLITEM DESC
) v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
WHERE v.rn <= 200
GROUP BY a.SEQPRODUTO, a.DESCCOMPLETA
ORDER BY SUM(v.VLRITEM - v.VLRDEVOLITEM) DESC`
}

// 8. PRODUTOS_ESTATISTICA
func (c *Concinco281) PRODUTOS_ESTATISTICA() string {
	return `SELECT 
    a.SEQPRODUTO AS EAN,
    a.DESCCOMPLETA AS DESCRICAO,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM) / SUM(v.QTDITEM), 2) AS VALOR_UNITARIO,
    SUM(v.QTDITEM) AS QUANTIDADE,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS TOTAL,
    ROUND(SUM(y.CMDIAVLRNF * v.QTDITEM), 2) AS CUSTO,
    ROUND(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 2) AS LUCRO
FROM (
    SELECT 
        v.SEQPRODUTO,
        v.VLRITEM,
        v.VLRDEVOLITEM,
        v.QTDITEM,
        v.SEQPRODUTOCUSTO,
        v.DTAVDA,
        v.NROEMPRESA,
        ROWNUM as rn
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
    ORDER BY v.VLRITEM - v.VLRDEVOLITEM DESC
) v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
WHERE v.rn <= 5000
GROUP BY a.SEQPRODUTO, a.DESCCOMPLETA
ORDER BY SUM(v.VLRITEM - v.VLRDEVOLITEM) DESC`
}

// 9. TOTAL_VENDIDO_POR_MODALIDADES
func (c *Concinco281) TOTAL_VENDIDO_POR_MODALIDADES() string {
	return `SELECT 
    fp.NROFORMAPAGTO AS CODIGO,
    NVL(fp.FORMAPAGTO, 'MODALIDADE DESCONHECIDA') AS DESCRICAO,
    COUNT(DISTINCT v.ROWIDDOCTO) AS QUANTIDADE,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS TOTAL
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MRL_FORMAPAGTO fp ON fp.NROFORMAPAGTO = v.NROFORMAPAGTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY fp.NROFORMAPAGTO, NVL(fp.FORMAPAGTO, 'MODALIDADE DESCONHECIDA')
ORDER BY TOTAL DESC`
}

// 10. ESTORNO_DE_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) ESTORNO_DE_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    df.NROECF AS PDV,
    TO_CHAR(df.DTAHOREMISSAO, 'DD/MM/YYYY') AS DATA,
    TO_CHAR(df.DTAHOREMISSAO, 'HH24:MI:SS') AS HORA,
    NVL(u.NOME, 'OPERADOR DESCONHECIDO') AS OPERADOR,
    NVL(df.USUCANCELOU, 'SEM SUPERVISOR') AS SUPERVISOR,
    ROUND(SUM(i.VLRITEM), 2) AS VALOR,
    df.NUMERODF AS CUPOM
FROM MFL_DOCTOFISCAL df
INNER JOIN MFL_DFITEM i ON (
    df.NUMERODF = i.NUMERODF
    AND df.NROEMPRESA = i.NROEMPRESA
    AND df.SERIEDF = i.SERIEDF
    AND df.SEQNF = i.SEQNF
)
LEFT JOIN GE_USUARIO u ON u.SEQUSUARIO = df.SEQOPERADOR
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'C'
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )
GROUP BY df.NROECF, df.DTAHOREMISSAO, df.DTAHOREMISSAO, NVL(u.NOME, 'OPERADOR DESCONHECIDO'), NVL(df.USUCANCELOU, 'SEM SUPERVISOR'), df.NUMERODF
ORDER BY DATA, HORA`
}

// 11. DESCONTOS_DE_ITENS_DIA
func (c *Concinco281) DESCONTOS_DE_ITENS_DIA() string {
	return `SELECT 
    TO_CHAR(df.DTAHOREMISSAO, 'DD/MM/YYYY') AS DATA,
    TO_CHAR(df.DTAHOREMISSAO, 'HH24:MI:SS') AS HORA,
    NVL(u.NOME, 'OPERADOR DESCONHECIDO') AS OPERADOR,
    NVL(df.USUCANCELOU, 'SEM SUPERVISOR') AS SUPERVISOR,
    ROUND(SUM(i.VLRDESCONTO), 2) AS VALOR,
    i.NUMERODF AS CUPOM,
    i.SEQPRODUTO AS ITEM,
    i.CODPRODUTO AS EAN,
    p.DESCCOMPLETA AS DESCRICAO
FROM MFL_DOCTOFISCAL df
INNER JOIN MFL_DFITEM i ON (
    df.NUMERODF = i.NUMERODF
    AND df.NROEMPRESA = i.NROEMPRESA
    AND df.SERIEDF = i.SERIEDF
    AND df.SEQNF = i.SEQNF
)
INNER JOIN MAP_PRODUTO p ON i.SEQPRODUTO = p.SEQPRODUTO
LEFT JOIN GE_USUARIO u ON u.SEQUSUARIO = df.SEQOPERADOR
WHERE df.DTAMOVIMENTO = TO_DATE(:1, 'DD/MM/YYYY')
  AND df.NROEMPRESA = :2
  AND df.STATUSDF = 'V'
  AND i.STATUSITEM = 'V'
  AND i.VLRDESCONTO > 0
  AND df.CODGERALOPER IN (
      SELECT cgo.CODGERALOPER
      FROM MAX_CODGERALOPER cgo
      WHERE cgo.TIPCGO = 'S'
        AND cgo.TIPUSO = 'E'
        AND cgo.TIPDOCFISCAL = 'C'
  )
GROUP BY 
    TO_CHAR(df.DTAHOREMISSAO, 'DD/MM/YYYY'),
    TO_CHAR(df.DTAHOREMISSAO, 'HH24:MI:SS'),
    NVL(u.NOME, 'OPERADOR DESCONHECIDO'),
    NVL(df.USUCANCELOU, 'SEM SUPERVISOR'),
    i.NUMERODF,
    i.SEQPRODUTO,
    i.CODPRODUTO,
    p.DESCCOMPLETA
ORDER BY DATA, HORA, VALOR DESC`
}

// 12. VENDAS_POR_SECOES_DIA
func (c *Concinco281) VENDAS_POR_SECOES_DIA() string {
	return `WITH produtos_categoria AS (
    SELECT DISTINCT
        v.SEQPRODUTO,
        FIRST_VALUE(cat.SEQCATEGORIA) OVER (
            PARTITION BY v.SEQPRODUTO 
            ORDER BY cat.SEQCATEGORIA
        ) AS SEQCATEGORIA_N2,
        FIRST_VALUE(cat.CATEGORIA) OVER (
            PARTITION BY v.SEQPRODUTO 
            ORDER BY cat.SEQCATEGORIA
        ) AS CATEGORIA_N2
    FROM MAXV_ABCDISTRIBBASE v
    INNER JOIN MAP_PRODUTO a ON a.SEQPRODUTO = v.SEQPRODUTO
    LEFT JOIN MAP_FAMDIVISAO d ON d.SEQFAMILIA = a.SEQFAMILIA
    LEFT JOIN MAP_FAMDIVCATEG u ON (
        u.SEQFAMILIA = d.SEQFAMILIA
        AND u.NRODIVISAO = d.NRODIVISAO
    )
    LEFT JOIN MAXV_CATEGORIA cat ON (
        cat.SEQCATEGORIA = u.SEQCATEGORIA
        AND cat.NRODIVISAO = u.NRODIVISAO
        AND cat.NIVELHIERARQUIA = 2
        AND cat.STATUSCATEGOR != 'I'
        AND cat.TIPCATEGORIA = 'M'
    )
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
)
SELECT 
    COALESCE(pc.SEQCATEGORIA_N2, 0) AS CODIGO,
    COALESCE(pc.CATEGORIA_N2, 'SEM CATEGORIA NIVEL 2') AS DESCRICAO,
    ROUND(SUM(v.QTDITEM), 2) AS QUANTIDADE,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS VALOR,
    ROUND(SUM(y.CMDIAVLRNF * v.QTDITEM), 2) AS CUSTO,
    ROUND(SUM((v.VLRITEM - v.VLRDEVOLITEM) - (y.CMDIAVLRNF * v.QTDITEM)), 2) AS LUCRO
FROM MAXV_ABCDISTRIBBASE v
INNER JOIN MRL_CUSTODIA y ON (
    y.SEQPRODUTO = v.SEQPRODUTOCUSTO
    AND y.DTAENTRADASAIDA = v.DTAVDA
    AND y.NROEMPRESA = v.NROEMPRESA
)
LEFT JOIN produtos_categoria pc ON pc.SEQPRODUTO = v.SEQPRODUTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY COALESCE(pc.SEQCATEGORIA_N2, 0), COALESCE(pc.CATEGORIA_N2, 'SEM CATEGORIA NIVEL 2')
ORDER BY VALOR DESC`
}

// 13. TOTAL_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) TOTAL_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    COUNT(DISTINCT cupom_valor.ROWIDDOCTO) AS QTD_CUPONS,
    cupom_valor.OPERADOR,
    ROUND(SUM(cupom_valor.VALOR), 2) AS VALOR
FROM (
    SELECT DISTINCT
        v.ROWIDDOCTO,
        NVL(TRIM(v.OPERADOR), 'OPERADOR SEM DESCRIÇÃO') AS OPERADOR,
        SUM(v.VLRITEM - v.VLRDEVOLITEM) OVER (PARTITION BY v.ROWIDDOCTO) AS VALOR
    FROM MAXV_ABCDISTRIBBASE v
    WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
      AND v.NROEMPRESA = :2
      AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
) cupom_valor
GROUP BY cupom_valor.OPERADOR
ORDER BY QTD_CUPONS DESC`
}

// 14. VENDAS_POR_VENDEDOR_DIA
func (c *Concinco281) VENDAS_POR_VENDEDOR_DIA() string {
	return `SELECT 
    TO_CHAR(v.DTAVDA, 'DD/MM/YYYY') AS DATA,
    NVL(j.APELIDO, 'SEM VENDEDOR') AS VENDEDOR,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS VALOR,
    COUNT(DISTINCT v.ROWIDDOCTO) AS CUPONS,
    ROUND(SUM(v.QTDITEM), 0) AS ITEM,
    ROUND(SUM(v.QTDITEM) / COUNT(DISTINCT v.ROWIDDOCTO), 2) AS MEDIA_ITENS,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM) / COUNT(DISTINCT v.ROWIDDOCTO), 2) AS MEDIA_VALOR
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MAD_REPRESENTANTE j ON j.NROREPRESENTANTE = v.NROREPRESENTANTE
LEFT JOIN GE_PESSOA rpe ON rpe.SEQPESSOA = j.SEQPESSOA
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY TO_CHAR(v.DTAVDA, 'DD/MM/YYYY'), NVL(j.APELIDO, 'SEM VENDEDOR')
ORDER BY VALOR DESC`
}

// 15. MODALIDADES_PAGAMENTO_OPERADOR_DIA
func (c *Concinco281) MODALIDADES_PAGAMENTO_OPERADOR_DIA() string {
	return `SELECT 
    TO_CHAR(v.DTAVDA, 'DD/MM/YYYY') AS DATA,
    NVL(TRIM(v.OPERADOR), 'OPERADOR DESCONHECIDO') AS OPERADOR,
    fp.NROFORMAPAGTO AS COD_PAGTO,
    NVL(fp.FORMAPAGTO, 'MODALIDADE SEM DESCRIÇÃO') AS DESCRICAO,
    COUNT(DISTINCT v.ROWIDDOCTO) AS QTD,
    ROUND(SUM(v.VLRITEM - v.VLRDEVOLITEM), 2) AS VALOR
FROM MAXV_ABCDISTRIBBASE v
LEFT JOIN MRL_FORMAPAGTO fp ON fp.NROFORMAPAGTO = v.NROFORMAPAGTO
WHERE v.DTAVDA = TO_DATE(:1, 'DD/MM/YYYY')
  AND v.NROEMPRESA = :2
  AND DECODE(v.TIPTABELA, 'S', v.CGOACMCOMPRAVENDA, v.ACMCOMPRAVENDA) IN ('S', 'I')
GROUP BY 
    TO_CHAR(v.DTAVDA, 'DD/MM/YYYY'),
    NVL(TRIM(v.OPERADOR), 'OPERADOR DESCONHECIDO'),
    fp.NROFORMAPAGTO,
    NVL(fp.FORMAPAGTO, 'MODALIDADE SEM DESCRIÇÃO')
ORDER BY DATA, OPERADOR, COD_PAGTO`
}
