package concinco

type Concinco281 struct{}

// 1. TOTAL_VENDIDO_DIA - Retorna valor, custo e lucro
func (c *Concinco281) TOTAL_VENDIDO_DIA() string {
	return `SELECT 
        sum((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) AS VENDA, 
        sum(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - nvl(Y.CMDIACREDPIS, 0) - nvl(Y.CMDIACREDCOFINS, 0) - nvl(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
            CASE WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                ELSE 1 
            END * 
            DECODE('S', 'N', 1, NVL(a.propqtdprodutobase, 1)) - 
            (decode(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(a.propqtdprodutobase, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
            decode(V.ACMCOMPRAVENDA, 'N', 0, decode('N', 'S', 0, (decode(nvl(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(a.propqtdprodutobase, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
            (V.QTDITEM - V.QTDDEVOLITEM)) AS CUSTO, 
        round(sum((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) - 
            sum(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - nvl(Y.CMDIACREDPIS, 0) - nvl(Y.CMDIACREDCOFINS, 0) - nvl(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
                CASE WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                    THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                    ELSE 1 
                END * 
                DECODE('S', 'N', 1, NVL(a.propqtdprodutobase, 1)) - 
                (decode(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(a.propqtdprodutobase, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
                decode(V.ACMCOMPRAVENDA, 'N', 0, decode('N', 'S', 0, (decode(nvl(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(a.propqtdprodutobase, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
                (V.QTDITEM - V.QTDDEVOLITEM)), 2) AS LUCRO 
    FROM 
        MRL_CUSTODIA Y, 
        MAXV_ABCDISTRIBBASE V, 
        MAP_PRODUTO A, 
        MAP_PRODUTO PB, 
        MAP_FAMDIVISAO D, 
        MAP_FAMEMBALAGEM K, 
        MAX_EMPRESA E, 
        MAX_DIVISAO DV, 
        MAP_PRODACRESCCUSTORELAC PR 
    WHERE 
        D.SEQFAMILIA = A.SEQFAMILIA 
        AND D.NRODIVISAO = V.NRODIVISAO 
        AND V.SEQPRODUTO = A.SEQPRODUTO 
        AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
        AND V.NRODIVISAO = D.NRODIVISAO 
        AND E.NROEMPRESA = V.NROEMPRESA 
        AND E.NRODIVISAO = DV.NRODIVISAO 
        AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
        AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
        AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
        AND V.NROEMPRESA = :ID
        AND Y.NROEMPRESA = nvl(E.NROEMPCUSTOABC, E.NROEMPRESA) 
        AND Y.DTAENTRADASAIDA = V.DTAVDA 
        AND K.SEQFAMILIA = A.SEQFAMILIA 
        AND K.QTDEMBALAGEM = 1 
        AND Y.SEQPRODUTO = PB.SEQPRODUTO 
        AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 2. TICKET_MEDIO_DIA
func (c *Concinco281) TICKET_MEDIO_DIA() string {
	return `SELECT 
    ROUND(
        CASE 
            WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
            ELSE SUM(((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) + NVL(VLREMBDESCRESSARCST, 0) - NVL(VLREMBDESCRESSARCSTDEVOL, 0)) / COUNT(DISTINCT V.ROWIDDOCTO) 
        END, 2
    ) AS TICKET_MEDIO
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 3. PRODUTOS_POR_ATENDIMENTO_DIA
func (c *Concinco281) PRODUTOS_POR_ATENDIMENTO_DIA() string {
	return `SELECT 
    ROUND(
        CASE 
            WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
            ELSE SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) / COUNT(DISTINCT V.ROWIDDOCTO) 
        END, 2
    ) AS MEDIA_ITENS
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 4. TOTAL_CUPONS_VALIDOS_DIA
func (c *Concinco281) TOTAL_CUPONS_VALIDOS_DIA() string {
	return `SELECT 
    COUNT(DISTINCT V.ROWIDDOCTO) AS CUPONS_VALIDOS
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I')`
}

// 5. TOTAL_CUPONS_CANCELADOS_DIA
func (c *Concinco281) TOTAL_CUPONS_CANCELADOS_DIA() string {
	return `SELECT 
    COUNT(1) AS CUPONS_CANCELADOS 
FROM 
    MFL_DOCTOFISCAL C 
WHERE 
    C.STATUSDF = 'C' 
    AND C.CODGERALOPER IN (
        SELECT XC.CODGERALOPER 
        FROM MAX_CODGERALOPER XC 
        WHERE XC.TIPCGO = 'S' 
        AND XC.TIPUSO = 'E' 
        AND XC.TIPDOCFISCAL = 'C'
    ) 
    AND C.DTAMOVIMENTO = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND C.NROEMPRESA = :ID`
}

// 6. VENDAS_POR_FAIXA_HORARIA
func (c *Concinco281) VENDAS_POR_FAIXA_HORARIA() string {
	return `SELECT 
    TO_CHAR(V.dtahorlancto, 'HH24') AS HORA, 
    SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) AS VALOR, 
    COUNT(DISTINCT V.ROWIDDOCTO) AS NUM_CUPONS, 
    ROUND(SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)), 0) AS NUM_ITENS, 
    CASE 
        WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
        ELSE ROUND(SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) / COUNT(DISTINCT V.ROWIDDOCTO), 2) 
    END AS MEDIA_ITENS, 
    CASE 
        WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
        ELSE ROUND(SUM(((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) + NVL(VLREMBDESCRESSARCST, 0) - NVL(VLREMBDESCRESSARCSTDEVOL, 0)) / COUNT(DISTINCT V.ROWIDDOCTO), 2) 
    END AS MEDIA_VALOR 
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    TO_CHAR(V.dtahorlancto, 'HH24') 
ORDER BY 
    HORA`
}

// 7. PRODUTOS_MAIS_VENDIDO_DIA
func (c *Concinco281) PRODUTOS_MAIS_VENDIDO_DIA() string {
	return `SELECT * FROM (
    SELECT 
        A.SEQPRODUTO AS EAN, 
        A.DESCCOMPLETA AS DESCRICAO, 
        CASE 
            WHEN SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) = 0 THEN 0 
            ELSE ROUND(SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) / SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)), 2)
        END AS VALOR_UNITARIO, 
        SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) AS QUANTIDADE, 
        SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) AS TOTAL, 
        SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
            CASE 
                WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                ELSE 1 
            END * 
            DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
            (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
            DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
            (V.QTDITEM - V.QTDDEVOLITEM)) AS CUSTO,
        ROUND(SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) - 
            SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
                CASE 
                    WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                    THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                    ELSE 1 
                END * 
                DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
                (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
                DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
                (V.QTDITEM - V.QTDDEVOLITEM)), 2) AS LUCRO
    FROM 
        MRL_CUSTODIA Y, 
        MAXV_ABCDISTRIBBASE V, 
        MAP_PRODUTO A, 
        MAP_PRODUTO PB, 
        MAP_FAMDIVISAO D, 
        MAP_FAMEMBALAGEM K, 
        MAX_EMPRESA E, 
        MAX_DIVISAO DV, 
        MAP_PRODACRESCCUSTORELAC PR 
    WHERE 
        D.SEQFAMILIA = A.SEQFAMILIA 
        AND D.NRODIVISAO = V.NRODIVISAO 
        AND V.SEQPRODUTO = A.SEQPRODUTO 
        AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
        AND V.NRODIVISAO = D.NRODIVISAO 
        AND E.NROEMPRESA = V.NROEMPRESA 
        AND E.NRODIVISAO = DV.NRODIVISAO 
        AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
        AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
        AND V.NROEMPRESA = :ID
        AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
        AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
        AND Y.DTAENTRADASAIDA = V.DTAVDA 
        AND K.SEQFAMILIA = A.SEQFAMILIA 
        AND K.QTDEMBALAGEM = 1 
        AND Y.SEQPRODUTO = PB.SEQPRODUTO 
        AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
    GROUP BY 
        A.SEQPRODUTO, 
        A.DESCCOMPLETA 
    ORDER BY 
        TOTAL DESC
) WHERE ROWNUM <= 200`
}

// 8. PRODUTOS_ESTATISTICA
// 8. PRODUTOS_ESTATISTICA (continuação)
func (c *Concinco281) PRODUTOS_ESTATISTICA() string {
	return `SELECT * FROM (
    SELECT 
        A.SEQPRODUTO AS EAN, 
        A.DESCCOMPLETA AS DESCRICAO, 
        CASE 
            WHEN SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) = 0 THEN 0 
            ELSE ROUND(SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) / SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)), 2)
        END AS VALOR_UNITARIO, 
        SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) AS QUANTIDADE, 
        SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) AS TOTAL, 
        SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
            CASE 
                WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                ELSE 1 
            END * 
            DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
            (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
            DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
            (V.QTDITEM - V.QTDDEVOLITEM)) AS CUSTO,
        ROUND(SUM((round(V.VLRITEM, 2)) - (round(V.VLRDEVOLITEM, 2) - (0))) - 
            SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
                CASE 
                    WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                    THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                    ELSE 1 
                END * 
                DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
                (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
                DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
                (V.QTDITEM - V.QTDDEVOLITEM)), 2) AS LUCRO
    FROM 
        MRL_CUSTODIA Y, 
        MAXV_ABCDISTRIBBASE V, 
        MAP_PRODUTO A, 
        MAP_PRODUTO PB, 
        MAP_FAMDIVISAO D, 
        MAP_FAMEMBALAGEM K, 
        MAX_EMPRESA E, 
        MAX_DIVISAO DV, 
        MAP_PRODACRESCCUSTORELAC PR 
    WHERE 
        D.SEQFAMILIA = A.SEQFAMILIA 
        AND D.NRODIVISAO = V.NRODIVISAO 
        AND V.SEQPRODUTO = A.SEQPRODUTO 
        AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
        AND V.NRODIVISAO = D.NRODIVISAO 
        AND E.NROEMPRESA = V.NROEMPRESA 
        AND E.NRODIVISAO = DV.NRODIVISAO 
        AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
        AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
        AND V.NROEMPRESA = :ID
        AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
        AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
        AND Y.DTAENTRADASAIDA = V.DTAVDA 
        AND K.SEQFAMILIA = A.SEQFAMILIA 
        AND K.QTDEMBALAGEM = 1 
        AND Y.SEQPRODUTO = PB.SEQPRODUTO 
        AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
    GROUP BY 
        A.SEQPRODUTO, 
        A.DESCCOMPLETA 
    ORDER BY 
        TOTAL DESC
) WHERE ROWNUM <= 5000`
}

// 9. TOTAL_VENDIDO_POR_MODALIDADES
func (c *Concinco281) TOTAL_VENDIDO_POR_MODALIDADES() string {
	return `SELECT 
    A2.NROFORMAPAGTO AS CODIGO, 
    NVL(A2.FORMAPAGTO, 'MODALIDADE DESCONHECIDA') AS DESCRICAO, 
    COUNT(DISTINCT V.ROWIDDOCTO) AS QUANTIDADE, 
    SUM((V.VLRITEM) - (V.VLRDEVOLITEM - (0))) AS TOTAL 
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR, 
    MRL_FORMAPAGTO A2 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND V.NROFORMAPAGTO = A2.NROFORMAPAGTO(+) 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    A2.NROFORMAPAGTO, 
    NVL(A2.FORMAPAGTO, 'MODALIDADE DESCONHECIDA') 
ORDER BY 
    TOTAL DESC`
}

// 10. ESTORNO_DE_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) ESTORNO_DE_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    C.NROECF AS PDV, 
    TO_CHAR(C.DTAHOREMISSAO, 'DD/MM/YYYY') AS DATA, 
    TO_CHAR(C.DTAHOREMISSAO, 'HH24:MI:SS') AS HORA, 
    U.NOME AS OPERADOR, 
    C.USUCANCELOU AS SUPERVISOR, 
    SUM(I.VLRITEM) AS VALOR, 
    C.NUMERODF AS CUPOM 
FROM 
    MFL_DOCTOFISCAL C, 
    MFL_DFITEM I, 
    GE_USUARIO U 
WHERE 
    C.NUMERODF = I.NUMERODF 
    AND C.NROEMPRESA = I.NROEMPRESA 
    AND C.SERIEDF = I.SERIEDF 
    AND C.SEQNF = I.SEQNF 
    AND C.STATUSDF = 'C' 
    AND C.SEQOPERADOR = U.SEQUSUARIO 
    AND C.CODGERALOPER IN (
        SELECT XC.CODGERALOPER 
        FROM MAX_CODGERALOPER XC 
        WHERE XC.TIPCGO = 'S' 
        AND XC.TIPUSO = 'E' 
        AND XC.TIPDOCFISCAL = 'C'
    ) 
    AND C.DTAMOVIMENTO = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND C.NROEMPRESA = :ID
GROUP BY 
    C.NROECF, 
    C.DTAHOREMISSAO, 
    U.NOME, 
    C.USUCANCELOU, 
    C.NUMERODF 
ORDER BY 
    C.DTAHOREMISSAO`
}

// 11. DESCONTOS_DE_ITENS_DIA
func (c *Concinco281) DESCONTOS_DE_ITENS_DIA() string {
	return `SELECT 
    TO_CHAR(C.DTAHOREMISSAO, 'DD/MM/YYYY') AS DATA, 
    TO_CHAR(C.DTAHOREMISSAO, 'HH24:MI:SS') AS HORA, 
    U.NOME AS OPERADOR, 
    C.USUAPLICADESC AS SUPERVISOR, 
    I.VLRDESCONTO AS VALOR, 
    I.NUMERODF AS CUPOM, 
    I.SEQPRODUTO AS ITEM, 
    I.CODPRODUTO AS EAN, 
    P.DESCCOMPLETA AS DESCRICAO 
FROM 
    MFL_DOCTOFISCAL C, 
    MFL_DFITEM I, 
    GE_USUARIO U, 
    MAP_PRODUTO P 
WHERE 
    C.NUMERODF = I.NUMERODF 
    AND C.NROEMPRESA = I.NROEMPRESA 
    AND C.SERIEDF = I.SERIEDF 
    AND C.SEQNF = I.SEQNF 
    AND I.SEQPRODUTO = P.SEQPRODUTO 
    AND C.STATUSDF = 'V' 
    AND C.SEQOPERADOR = U.SEQUSUARIO 
    AND C.CODGERALOPER IN (
        SELECT XC.CODGERALOPER 
        FROM MAX_CODGERALOPER XC 
        WHERE XC.TIPCGO = 'S' 
        AND XC.TIPUSO = 'E' 
        AND XC.TIPDOCFISCAL = 'C'
    ) 
    AND C.DTAMOVIMENTO = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND C.NROEMPRESA = :ID
    AND I.VLRDESCONTO > 0 
ORDER BY 
    C.DTAHOREMISSAO`
}

// 12. VENDAS_POR_SECOES_DIA
func (c *Concinco281) VENDAS_POR_SECOES_DIA() string {
	return `SELECT 
    G.SEQCATEGORIA AS CODIGO, 
    G.CATEGORIA AS DESCRICAO, 
    SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) AS QUANTIDADE, 
    SUM((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) AS VALOR, 
    SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
        CASE 
            WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
            THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
            ELSE 1 
        END * 
        DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
        (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
        DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
        (V.QTDITEM - V.QTDDEVOLITEM)) AS CUSTO,
    ROUND(SUM((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) - 
        SUM(((Y.CMDIAVLRNF + Y.CMDIAIPI - Y.CMDIACREDICMS - NVL(Y.CMDIACREDPIS, 0) - NVL(Y.CMDIACREDCOFINS, 0) - NVL(Y.CMDIACREDIPI, 0) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF) * 
            CASE 
                WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL 
                THEN COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1)) 
                ELSE 1 
            END * 
            DECODE('S', 'N', 1, NVL(A.PROPQTDPRODUTOBASE, 1)) - 
            (DECODE(Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, Y.QTDVERBAVDA, Y.QTDVDA))) + 
            DECODE(V.ACMCOMPRAVENDA, 'N', 0, DECODE('N', 'S', 0, (DECODE(NVL(Y.VLRVERBAVDAACR, 0), 0, 0, Y.VLRVERBAVDAACR * NVL(A.PROPQTDPRODUTOBASE, 1) / DECODE(NVL(Y.QTDVDA, 0), 0, 1, Y.QTDVDA)))))) * 
            (V.QTDITEM - V.QTDDEVOLITEM)), 2) AS LUCRO
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR, 
    MAXV_CATEGORIA G, 
    MAP_FAMDIVCATEG U 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND V.NROEMPRESA = :ID
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND U.SEQFAMILIA = D.SEQFAMILIA 
    AND U.NRODIVISAO = D.NRODIVISAO 
    AND U.SEQCATEGORIA = G.SEQCATEGORIA 
    AND U.NRODIVISAO = G.NRODIVISAO 
    AND U.STATUS = 'A' 
    AND G.STATUSCATEGOR != 'I' 
    AND G.TIPCATEGORIA = 'M' 
    AND G.NIVELHIERARQUIA = 1 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    G.SEQCATEGORIA, 
    G.CATEGORIA
ORDER BY 
    VALOR DESC`
}

// 13. TOTAL_CUPONS_POR_OPERADOR_DIA
func (c *Concinco281) TOTAL_CUPONS_POR_OPERADOR_DIA() string {
	return `SELECT 
    COUNT(DISTINCT V.ROWIDDOCTO) AS QTD_CUPONS, 
    NVL(TRIM(V.OPERADOR), 'OPERADOR SEM DESCRICAO') AS OPERADOR, 
    SUM((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) AS VALOR 
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    NVL(TRIM(V.OPERADOR), 'OPERADOR SEM DESCRICAO') 
ORDER BY 
    QTD_CUPONS DESC`
}

// 14. VENDAS_POR_VENDEDOR_DIA
func (c *Concinco281) VENDAS_POR_VENDEDOR_DIA() string {
	return `SELECT 
    TO_CHAR(V.DTAVDA, 'DD/MM/YYYY') AS DATA,
    NVL(J.APELIDO, 'Sem vendedor') AS VENDEDOR, 
    SUM((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) AS VALOR, 
    COUNT(DISTINCT V.ROWIDDOCTO) AS CUPONS, 
    SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) AS ITEM, 
    CASE 
        WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
        ELSE ROUND(SUM(ROUND((V.QTDITEM - V.QTDDEVOLITEM) / K.QTDEMBALAGEM, 6)) / COUNT(DISTINCT V.ROWIDDOCTO), 2) 
    END AS MEDIA_ITENS, 
    CASE 
        WHEN COUNT(DISTINCT V.ROWIDDOCTO) = 0 THEN 0 
        ELSE ROUND(SUM(((ROUND(V.VLRITEM, 2)) - (ROUND(V.VLRDEVOLITEM, 2) - (0))) + NVL(VLREMBDESCRESSARCST, 0) - NVL(VLREMBDESCRESSARCSTDEVOL, 0)) / COUNT(DISTINCT V.ROWIDDOCTO), 2) 
    END AS MEDIA_VALOR 
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR, 
    MAD_REPRESENTANTE J, 
    GE_PESSOA RPE 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND V.NROEMPRESA = :ID
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND V.NROREPRESENTANTE = J.NROREPRESENTANTE(+) 
    AND J.SEQPESSOA = RPE.SEQPESSOA(+) 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    TO_CHAR(V.DTAVDA, 'DD/MM/YYYY'),
    NVL(J.APELIDO, 'Sem vendedor')
ORDER BY 
    VALOR DESC`
}

// 15. MODALIDADES_PAGAMENTO_OPERADOR_DIA (continuação)
func (c *Concinco281) MODALIDADES_PAGAMENTO_OPERADOR_DIA() string {
	return `SELECT 
    TO_CHAR(V.DTAVDA, 'DD/MM/YYYY') AS DATA, 
    NVL(TRIM(V.OPERADOR), 'OPERADOR DESCONHECIDO') AS OPERADOR, 
    A2.NROFORMAPAGTO AS COD_PAGTO, 
    NVL(A2.FORMAPAGTO, 'MODALIDADE SEM DESCRICAO') AS DESCRICAO, 
    COUNT(DISTINCT V.ROWIDDOCTO) AS QTD, 
    SUM((V.VLRITEM) - (V.VLRDEVOLITEM - (0))) AS VALOR 
FROM 
    MRL_CUSTODIA Y, 
    MAXV_ABCDISTRIBBASE V, 
    MAP_PRODUTO A, 
    MAP_PRODUTO PB, 
    MAP_FAMDIVISAO D, 
    MAP_FAMEMBALAGEM K, 
    MAX_EMPRESA E, 
    MAX_DIVISAO DV, 
    MAP_PRODACRESCCUSTORELAC PR, 
    MRL_FORMAPAGTO A2 
WHERE 
    D.SEQFAMILIA = A.SEQFAMILIA 
    AND D.NRODIVISAO = V.NRODIVISAO 
    AND V.SEQPRODUTO = A.SEQPRODUTO 
    AND V.SEQPRODUTOCUSTO = PB.SEQPRODUTO 
    AND V.NRODIVISAO = D.NRODIVISAO 
    AND E.NROEMPRESA = V.NROEMPRESA 
    AND E.NRODIVISAO = DV.NRODIVISAO 
    AND V.SEQPRODUTO = PR.SEQPRODUTO(+) 
    AND V.DTAVDA = PR.DTAMOVIMENTACAO(+) 
    AND V.NROEMPRESA = :ID
    AND V.DTAVDA = TO_DATE(:DATA, 'DD-MM-YYYY')
    AND Y.NROEMPRESA = NVL(E.NROEMPCUSTOABC, E.NROEMPRESA) 
    AND Y.DTAENTRADASAIDA = V.DTAVDA 
    AND K.SEQFAMILIA = A.SEQFAMILIA 
    AND K.QTDEMBALAGEM = 1 
    AND Y.SEQPRODUTO = PB.SEQPRODUTO 
    AND V.NROFORMAPAGTO = A2.NROFORMAPAGTO(+) 
    AND DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) IN ('S', 'I') 
GROUP BY 
    A2.NROFORMAPAGTO, 
    TO_CHAR(V.DTAVDA, 'DD/MM/YYYY'), 
    NVL(A2.FORMAPAGTO, 'MODALIDADE SEM DESCRICAO'), 
    NVL(TRIM(V.OPERADOR), 'OPERADOR DESCONHECIDO') 
ORDER BY 
    OPERADOR, DESCRICAO`
}
